apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ${{topicName}}
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  namespace: klage
  labels:
    team: klage
spec:
  pool: {{pool}}
  config:
  {{#each config as |value key|}}
    {{key}}: {{value}}
  {{/each}}
  acl:
    - team: klage
      application: klage-kafka-manager
      access: read
  {{#each acl}}
    - team: {{team}}
      application: {{application}}
      access: {{access}}
  {{/each}}